arb-dir: ./l10n
template-arb-file: app_es.arb
output-dir: lib/src/l10n
synthetic-package: false
output-localization-file: app_localization.dart
output-class: AppLocalization
untranslated-messages-file: unstralated_messages.yaml
